# Generated by Django 2.2.2 on 2020-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
